WICG/virtual-scroller

demo/html-spec/html-spec-viewer.js
layouts/layout-1d-base.js
layouts/layout-1d-grid.js
layouts/layout-1d.js
smoke/flat/script.js
smoke/nested/script.js
virtual-list-element.js
virtual-list.js

x/y -> top/left or width/height

---

DESIGN.md
README.md

The content is very similar, just expanded a bit. This should be more like a web platform explainer.
Please review for accuracy; I might have gotten things wrong while explaining them more!

Flesh out README

---

README.md
demo/sorting.html
virtual-list-element.js
virtual-repeater.js

Fixes #32 
Added demo showing how using `itemKey` can affect rendering and animation

expose itemKey

---

demo/html-spec/html-spec-viewer.js
demo/html-spec/index.html

Fixes #19 by using VirtualList instead of the custom element, so that `body` selectors can work

Use VirtualList instead of <virtual-list>

---

README.md

Addresses #33 by providing an example in the README for "Clickable list elements"

Example with click listener

---

demo/html-spec/html-spec-viewer.js
demo/html-spec/index.html

Reverts valdrinkoshi/virtual-list#43

Revert "Use VirtualList instead of <virtual-list>"

---

README.md

Also update example headings to state what API they're explaining.
Feedback welcome!

Add a dedicated example for newChild/updateChild

---

README.md
demo/sorting.html
virtual-list-element.js
virtual-repeater.js

rename itemKey to childKey

---

demo/contacts/lit-html/contacts.js

restore dom, let lit-html handle the update

---

demo/contacts/lit-html/contacts.js

Reverts valdrinkoshi/virtual-list#57
(merged by accident :x )

Revert "restore dom, let lit-html handle the update"

---

virtual-list-element.js

Fixes #60 by loading layout classes synchronously.

Load layout classes synchronously

---

demo/photos/preact/photos.js

This fixes the horizontal scrolling mode of `demo/photos/preact/`

Fix preact photos demo

---

DESIGN.md
README.md
demo/basic-repeat/basic-repeat.js
demo/contacts/contacts.js
demo/fallback.html
demo/header-footer.html
demo/html-spec/html-spec-viewer.js
demo/layout.html
demo/photos/photos.js
demo/sorting.html
lit-html/lit-repeater.js
preact/preact-repeater.js
smoke/flat/script.js
smoke/infinite/index.html
smoke/nested/script.js
virtual-repeater.js
virtual-scroller-element.js

Fixes #25.
Renamed methods `new/update/recycleChild` to `create/update/recycleElement`, and `childKey` to `elementKey`.

*Child -> *Element

---

demo/html-spec/html-spec-viewer.js
package-lock.json

Workaround for https://crbug.com/846322
Fixes #82

Hide url bar on scroll

---

demo/dismissable/dismissable-item.js
demo/dismissable/index.html

Also encapsulate the overflow-x: hidden in the shadow root

Use a content wrapper for applying transform to

---

demo/dismissable/dismissable-item.js
demo/dismissable/index.html

Needed overflow:hidden on content wrapper as well

Misc fixes to dismissable demo

---

demo/index.html
demo/loadmore.html

Addresses #33 - P1 "load more" example

Add loadmore example

---

virtual-scroller-element.js

remove identity check

---

demo/html-spec-native-lapi/html-spec-viewer.js
demo/html-spec-native-lapi/index.html

Synced to latest version as https://chromium-review.googlesource.com/c/chromium/src/+/1106905 was merged and is available in Canary 69.0.3473.0

update to latest deployment

---

README.md
demo/sorting.html
item-source.js

use index as elementKey

---

README.md

* Fix a few typos in the code samples.
* Add a pointer to #101 for anyone interested.
* Explain the relation with the template instantiation proposal, and our thoughts on future compatibility. Fixes #98.

Expand on <template>-based element creation

---

demo/loadmore.html

Use contacts as item keys, so that when new data is received, the index previously containing the button will be updated.
(I realized only now I didn't commit this change which was sitting there in my laptop for the last 2 months, lol)

bugfix: demo/loadmore.html

---

demo/basic-repeat/lit-html/basic-repeat.js
demo/contacts/lit-html/contacts.js
demo/photos/lit-html/photos.js
lit-html/lit-repeater.js
lit-html/lit-scroller.js
package-lock.json
smoke/flat/script.js
virtual-repeater.js

Fixes #134 by integrating to lit-html 0.13.0
Also, maintain dom order (regression introduced in #135)

Integrate with lit-html 0.13

---

README.md

Feel free to decline or modify this! Thanks for the awesome explainer

Grammatical changes

---

study-group/Angular-Material-virtual-scroll.md
study-group/Polymer-iron-list.md
study-group/README.md
study-group/REQUIREMENTS.md
study-group/WinJS.md
study-group/iOS-UITableView.md

We'd like to consolidate that repository into this one. I'll merge this PR shortly, as well as re-creating some of the issues, unless folks have any comments or thoughts.

Move the contents of domenic/infinite-list-study-group here

---

demo/index.html

add demo/index.html

---

demo/loadmore.html

Very basic, just replaced the load-more button with a DIV and uses default intersection observer to spot when it has been scrolled into view. I decided against using a buffer on the intersection observer to preload the content because I want it to be clearly visible what is going on.

add automatic load more

---

demo/simple/index.html
demo/simple/move-first-child.html
demo/simple/resize-font.html
demo/simple/resize.html
demo/simple/restyle.html
demo/simple/scaffolding.mjs
demo/simple/scroll.html
demo/util/demo-controller.mjs
demo/util/fps-display.mjs
demo/util/util.mjs

Add several simple demos. 
Also adds some custom elements that are share among these and other demos.

Fergald simple demos

---

.clang-format
demo/contacts/contact-element.mjs
demo/util/demo-controller.mjs
demo/util/fps-display.mjs
demo/util/util.mjs

This is chromium's .clang-format file.

add .clang-format file and reformat all .mjs files

---

demo/sticky.html

Add a button that enables an FPS display and animates resizing the contact list horizontally. Between virtual-scroller and raw divs demonstrates clear drop in FPS and increase in CPU.

add performance demo mode

---

demo/contacts/contact-data-source.mjs
demo/contacts/contact-element.mjs
demo/util/demo-controller.mjs
demo/util/fps-display.mjs

Many browsers don't support `#privateName` private fields in JS. Stop using them.
Fixes #180

Fergald no private fields
